import {load,save} from './store.js';
let state=load(),page='Today',preview=null;
const app=document.querySelector('#app');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d;});
const date=d=>d.toLocaleDateString('en-PH',{weekday:'short',month:'short',day:'numeric',timeZone:'Asia/Manila'});
function persist(){try{save(state);render();}catch{alert('Changes could not be saved. Export a backup from Settings.');}}
function card(t){return `<article class="task ${t.status}"><small>${esc(t.course)} · ${esc(t.status)}</small><h3>${esc(t.title)}</h3><p>${date(days[t.day])} · ${esc(t.time)} · ${t.minutes} min remaining</p><div class="actions"><button data-done="${t.id}">Done</button><button data-miss="${t.id}">Missed / recover</button></div></article>`;}
function render(){const pending=state.tasks.filter(t=>t.status!=='done');app.innerHTML=`<aside><h2>WeekBack</h2><p class="muted">Quiet academic planner</p><nav>${['Today','Week','Tasks','Settings'].map(x=>`<button data-page="${x}" class="${page===x?'active':''}">${x}</button>`).join('')}</nav><small class="side-note">Asia/Manila · Saved in this browser</small></aside><section class="workspace"><header><span>${date(days[0])}</span><span class="badge">${navigator.onLine?'Local storage':'Offline'} · AI not connected</span><button class="primary" id="add">+ Add task</button></header><main><p class="eyebrow">YOUR WEEK, WITH ROOM TO CHANGE</p><h1>${preview?'Plan recovery preview':page}</h1>${preview?recovery():page==='Today'?`<section class="hero"><small>NEXT UP</small>${pending[0]?card(pending[0]):'<h2>All caught up.</h2>'}</section><div class="columns"><section><h2>Your agenda</h2>${state.tasks.map(card).join('')}</section><section><h2>Approaching deadlines</h2><p class="muted">Initial demo tasks. Add your own to get started.</p>${pending.map(t=>`<article class="panel"><b>${esc(t.course)}</b><p>${esc(t.title)}</p><small>${t.minutes} min remaining</small></article>`).join('')}</section></div>`:page==='Week'?`<p class="muted">Next seven days · select a task to update progress</p><div class="week">${days.map((d,i)=>`<section><h3>${date(d)}</h3>${state.tasks.filter(t=>t.day===i).map(card).join('')||'<p class="muted">Free space</p>'}</section>`).join('')}</div>`:page==='Tasks'?state.tasks.map(card).join(''):`<section class="panel"><h2>Local data</h2><p>Your tasks stay in this browser. Export before clearing browser data.</p><button id="export">Export JSON backup</button><h2>Local AI</h2><p>Not connected in this initial version. Task entry is manual; scheduling and AI interpretation are next implementation modules.</p></section>`}</main></section><dialog id="task-dialog"><form id="task-form"><div class="dialog-head"><h2>Add task</h2><button type="button" id="close">Close</button></div><p class="muted">Manual entry · local AI integration pending</p><label>Task title<input name="title" required maxlength="180"></label><label>Course<input name="course" required maxlength="40"></label><div class="form-row"><label>Estimated minutes<input name="minutes" type="number" min="15" max="1440" value="60" required></label><label>Day<select name="day">${days.map((d,i)=>`<option value="${i}">${date(d)}</option>`).join('')}</select></label><label>Start time<input name="time" type="time" value="14:00" required></label></div><button class="primary">Save task</button></form></dialog>`;
app.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;preview=null;render();});
app.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{state.tasks.find(t=>t.id===b.dataset.done).status='done';persist();});
app.querySelectorAll('[data-miss]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(t=>t.id===b.dataset.miss);preview={id:t.id,day:Math.min(6,t.day+1)};render();});
document.querySelector('#add').onclick=()=>document.querySelector('dialog').showModal();document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();
document.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.tasks.push({id:crypto.randomUUID(),title:f.get('title').trim(),course:f.get('course').trim(),minutes:Number(f.get('minutes')),day:Number(f.get('day')),time:f.get('time'),status:'planned'});persist();};
const accept=document.querySelector('#accept');if(accept)accept.onclick=()=>{state.previous=structuredClone(state.tasks);const t=state.tasks.find(t=>t.id===preview.id);t.day=preview.day;preview=null;persist();};
const cancel=document.querySelector('#cancel');if(cancel)cancel.onclick=()=>{preview=null;render();};
const undo=document.querySelector('#undo');if(undo)undo.onclick=()=>{state.tasks=state.previous;state.previous=null;persist();};
const ex=document.querySelector('#export');if(ex)ex.onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,...state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='weekback-backup.json';a.click();URL.revokeObjectURL(u);};
if(state.previous&&!preview){const b=document.createElement('button');b.id='undo';b.textContent='Undo last recovery';b.onclick=()=>{state.tasks=state.previous;state.previous=null;persist();};document.querySelector('main').prepend(b);}}
function recovery(){const t=state.tasks.find(t=>t.id===preview.id);return `<section class="panel"><span class="badge">Demonstration proposal</span><h2>${esc(t.title)}</h2><p>${date(days[t.day])} → ${date(days[preview.day])} at ${esc(t.time)}</p><p>This initial preview moves the task to the following day. Conflict checking and deadline-aware scheduling are not implemented yet.</p><div class="actions"><button id="cancel">Keep current plan</button><button id="accept" class="primary">Accept demo move</button></div></section>`;}
render();window.addEventListener('online',render);window.addEventListener('offline',render);
