import {loadState,saveState,exportState,importState,loadDemoFixtures,recordProgress} from './store.js';
import {formatDate,formatTime,formatDateTime,toLocalDateAndTime,parseInTimezone,diffMinutes} from './dates.js';
import {getAIStatus} from './ai-client.js';
import {openPlanner} from './integrated-planner.js';
import {showTaskForm} from './task-capture.js';
import {assistantPage} from './assistant-ui.js';
let state=loadState(),page='Today',offset=0,agendaMode='timeline',weekMode='grid',notice='',failed=false,assistantDraft='';
let ai={ready:false,models:[],error:null,checking:true};
const app=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<img class="icon" src="/public/icons/${name}.svg" alt="" aria-hidden="true">`;
const todayDate=()=>toLocalDateAndTime(new Date()).date;
const dateAt=n=>{const d=new Date(todayDate()+'T12:00:00+08:00');d.setUTCDate(d.getUTCDate()+n);return toLocalDateAndTime(d).date;};
const label=n=>formatDate(parseInTimezone(dateAt(n),'12:00'));
const task=id=>state.tasks.find(t=>t.id===id);
const tone=t=>/KAS|HIST/.test(t?.course)?'terracotta':/CS|STAT/.test(t?.course)?'sage':'blue';
const aiLabel=()=>ai.checking?'Checking local AI…':ai.ready?'Ready · qwen3.5:2b':ai.modelMissing?'Model not installed':ai.offline?'Offline':'Not running';
function persist(message='',refresh=true){try{saveState(state);failed=false;notice=message;}catch(error){failed=true;notice=error.message;}if(refresh)render();return {ok:!failed,message:notice};}
async function probe(){ai.checking=true;updateStatus();try{const result=await getAIStatus();const installed=result.models.some(name=>name==='qwen3.5:2b');ai={...result,ready:result.ready&&installed,modelMissing:result.ready&&!installed,offline:!result.ready&&!navigator.onLine,checking:false};if(ai.modelMissing)ai.error='Ollama is running. Install qwen3.5:2b to interpret tasks.';}catch(error){ai={ready:false,models:[],error:error.message,offline:true,checking:false};}updateStatus();}
function updateStatus(){app.querySelectorAll('[data-ai-status]').forEach(el=>el.textContent=aiLabel());app.querySelectorAll('[data-ai-error]').forEach(el=>el.textContent=ai.error||'');}
function sessions(){return [...state.blocks.filter(b=>task(b.taskId)).map(b=>({...b,title:task(b.taskId).title,course:task(b.taskId).course,kind:'study'})),...state.commitments.map(c=>({...c,course:'FIXED COMMITMENT',kind:'fixed',status:'fixed'}))].sort((a,b)=>a.startAt.localeCompare(b.startAt));}
const range=b=>formatTime(b.startAt)+' – '+formatTime(b.endAt);
function row(b,nextId){return `<div class="agenda-row ${b.status==='completed'?'complete':''}"><span class="timeline-marker ${b.id===nextId?'current':''}">${icon(b.kind==='fixed'?'lock-keyhole':'book-open')}</span><article class="agenda-card ${tone(b)} ${b.kind==='fixed'?'fixed-card':''}"><div class="agenda-card-top"><small>${esc(b.course)}</small><span class="status-tag">${esc(b.status.replaceAll('_',' '))}</span></div><h3>${esc(b.title)}</h3><div class="agenda-card-bottom"><span>${range(b)}</span><button class="text-button" data-session="${esc(b.id)}">Manage session</button></div></article></div>`;}
function today(){const agenda=sessions().filter(b=>toLocalDateAndTime(b.startAt).date===todayDate()),next=agenda.find(b=>b.kind==='study'&&b.status==='planned'&&task(b.taskId).status!=='done'),t=next&&task(next.taskId);return `<span class="eyebrow">ACADEMIC LEDGER · YOUR WEEK AT A GLANCE</span><h1>Today</h1>${next?`<section class="hero ${tone(t)}"><div class="hero-main"><div class="hero-kicker"><span class="course-tag">${esc(t.course)}</span><span>Next planned session</span></div><h2>${esc(t.title)}</h2><div class="hero-meta"><strong>${range(next)}</strong><span>${diffMinutes(next.startAt,next.endAt)} min planned</span></div><div class="immediate-step"><small>IMMEDIATE STEP</small><p>${esc(t.steps.find(s=>!s.completed)?.title||'Open your materials and continue your task.')}</p></div><p class="remaining">${t.remainingMinutes} min remaining · ${t.dueAt?'Due '+formatDateTime(t.dueAt):'No deadline entered'}</p></div><div class="hero-actions"><button class="primary" data-session="${esc(next.id)}">Start session</button><div class="progress-actions"><button class="soft" data-done="${esc(next.id)}">Done</button><button class="soft" data-session="${esc(next.id)}">Partial</button><button class="soft" data-missed="${esc(next.id)}">Missed</button></div></div></section>`:`<section class="hero empty"><h2>A little room for what comes next.</h2><p>Add tasks, enter availability, then preview your study plan.</p><button class="primary" data-add>Add task</button><button class="soft" data-planner>Plan my week</button></section>`}<div class="today-columns"><section class="panel agenda"><div class="panel-title"><div><h2>Today’s Agenda</h2><p>${label(0)} · ${agenda.length} sessions</p></div><div class="segmented"><button data-agenda="timeline" class="${agendaMode==='timeline'?'chosen':''}">Timeline</button><button data-agenda="list" class="${agendaMode==='list'?'chosen':''}">List</button></div></div><div class="agenda-items ${agendaMode}">${agenda.map(b=>row(b,next?.id)).join('')||'<p>No sessions scheduled today.</p>'}</div></section><div class="right-column"><section class="panel"><h2>Keep the week workable</h2><p>Review schedule changes before applying them.</p><button class="primary" data-planner>Preview recovery</button></section><section class="panel deadlines"><h2>Upcoming Work</h2>${state.tasks.filter(t=>t.status==='open').map(t=>`<button class="deadline-card ${tone(t)}" data-edit="${esc(t.id)}"><strong>${esc(t.title)}</strong><span class="deadline-meta"><small>${t.remainingMinutes} min remaining</small><small>${t.dueAt?formatDate(t.dueAt):'No deadline'}</small></span></button>`).join('')||'<p>No open tasks.</p>'}</section></div></div>`;}
function week(){const days=Array.from({length:7},(_,i)=>dateAt(offset+i)),visible=sessions().filter(b=>days.includes(toLocalDateAndTime(b.startAt).date));return `<h1>Week</h1><button class="primary" data-planner>Manage study plan & recovery</button><div class="week-summary"><div><span class="eyebrow">PLANNED STUDY</span><strong>${(visible.filter(b=>b.kind==='study').reduce((s,b)=>s+diffMinutes(b.startAt,b.endAt),0)/60).toFixed(1)} <small>hrs</small></strong></div><div><span class="eyebrow">OPEN TASKS</span><strong>${new Set(visible.filter(b=>b.taskId&&task(b.taskId).status==='open').map(b=>b.taskId)).size}</strong></div><div class="week-tools segmented"><button data-week="grid" class="${weekMode==='grid'?'chosen':''}">Grid</button><button data-week="list" class="${weekMode==='list'?'chosen':''}">List view</button></div></div>${weekMode==='list'?`<section class="panel">${days.map((d,i)=>`<h2>${label(offset+i)}</h2>${visible.filter(b=>toLocalDateAndTime(b.startAt).date===d).map(b=>row(b)).join('')||'<p>No sessions scheduled.</p>'}`).join('')}</section>`:`<section class="calendar"><div class="calendar-head"><div>Time</div>${days.map((d,i)=>`<div><small>${label(offset+i)}</small></div>`).join('')}</div><div class="calendar-scroll"><div class="calendar-body"><div class="time-gutter">${Array.from({length:24},(_,i)=>`<span style="top:${i*120}px">${String(i).padStart(2,'0')}:00</span>`).join('')}</div>${days.map(d=>`<div class="day-column">${visible.filter(b=>toLocalDateAndTime(b.startAt).date===d).map(b=>{const [h,m]=toLocalDateAndTime(b.startAt).time.split(':').map(Number);return `<button class="calendar-block ${tone(b)} ${b.kind==='fixed'?'fixed-block':''}" data-session="${esc(b.id)}" style="top:${(h*60+m)*2}px;height:${Math.max(30,Math.min(diffMinutes(b.startAt,b.endAt),1440-h*60-m)*2)}px"><span class="block-top">${esc(b.course)}</span><strong>${esc(b.title)}</strong><small>${range(b)}</small></button>`;}).join('')}</div>`).join('')}</div></div></section>`}`;}
function tasks(){return `<h1>Tasks</h1><section class="panel task-table">${state.tasks.map(t=>`<div class="task-table-row"><div><small>${esc(t.course)}</small><h3>${esc(t.title)}</h3><span class="status-tag">${esc(t.status)}</span></div><span>${t.dueAt?formatDateTime(t.dueAt):'No deadline'}</span><span>${t.remainingMinutes} min</span><div class="actions"><button class="soft" data-edit="${esc(t.id)}">Edit</button><button data-delete="${esc(t.id)}" aria-label="Delete ${esc(t.title)}">Delete</button></div></div>`).join('')||'<p>Add your first task to begin.</p>'}</section>`;}
function settings(){return `<h1>Settings</h1><div class="settings-grid"><section class="panel"><h2>Local data</h2><p>Stable dates in Philippine time. Your data stays in this browser.</p><button class="primary" data-export>Export JSON backup</button><label>Import backup<input id="backup-file" type="file" accept=".json,application/json"></label><p>Import replaces the current planner after confirmation.</p><hr><button class="soft" data-sample>Load sample week</button></section><section class="panel"><h2>Local AI</h2><span class="pill model" data-ai-status>${esc(aiLabel())}</span><p data-ai-error>${esc(ai.error||'')}</p><button class="soft" data-probe>Check connection</button><p>Start Ollama and install qwen3.5:2b to interpret tasks locally. Manual entry works without a model.</p><p>Schedule chat is not supported yet.</p></section></div>`;}
function assistant(){return assistantPage(assistantDraft,aiLabel());}
function render(){const nav={Today:'calendar',Week:'columns-3',Tasks:'circle-check',Assistant:'notebook',Settings:'settings-2'};app.innerHTML=`<aside class="sidebar"><div class="brand"><img class="brand-logo" src="/public/waypoint-logo.png" alt=""><span>Waypoint</span></div><nav aria-label="Main navigation">${Object.entries(nav).map(([name,i])=>`<button class="nav-item ${page===name?'selected':''}" data-page="${name}" ${page===name?'aria-current="page"':''}>${icon(i)}${name==='Assistant'?'Ask Waypoint':name}</button>`).join('')}</nav></aside><div class="workspace"><header class="topbar"><div class="date-controls"><div class="week-switch"><button data-shift="-7" aria-label="Previous week">${icon('chevron-left')}</button><span>${label(offset)} – ${label(offset+6)}</span><button data-shift="7" aria-label="Next week">${icon('chevron-right')}</button></div><button class="soft" data-page="Today">Today</button></div><div class="connection"><span class="pill ${failed?'error-pill':'saved'}">${failed?'Save failed':'Saved on this device'}</span><span class="pill model" data-ai-status>${esc(aiLabel())}</span></div><button class="primary" data-add>${icon('plus')} Add Task</button></header><main>${notice?`<div class="notice ${failed?'warning':''}" role="${failed?'alert':'status'}">${esc(notice)}<button data-dismiss aria-label="Dismiss notice">Close</button></div>`:''}${page==='Today'?today():page==='Week'?week():page==='Tasks'?tasks():page==='Assistant'?assistant():settings()}</main></div>`;const grid=app.querySelector('.calendar-scroll');if(grid)grid.scrollTop=960;resizeDraft();}
function resizeDraft(){const field=app.querySelector('#assistant-draft');if(field){field.style.height='auto';field.style.height=(field.scrollHeight+field.offsetHeight-field.clientHeight)+'px';}}
function confirmAction(title,message,action){app.insertAdjacentHTML('beforeend',`<dialog id="confirm-dialog"><div class="dialog-body"><h2>${esc(title)}</h2><p>${esc(message)}</p><div class="actions"><button data-confirm-cancel>Cancel</button><button class="primary" data-confirm>Confirm</button></div></div></dialog>`);const d=app.querySelector('#confirm-dialog');d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{e.stopPropagation();if(e.target.closest('[data-confirm-cancel]'))d.close();if(e.target.closest('[data-confirm]')){d.close();action();}});d.showModal();}
app.addEventListener('click',e=>{const d=e.target.closest('button')?.dataset;if(!d)return;
 if(d.page){page=d.page;render();if(page==='Settings'||page==='Assistant')probe();}
 else if(d.shift){offset+=Number(d.shift);page='Week';render();}
 else if('add'in d)showTaskForm(app,state,persist,ai);
 else if('capture'in d)showTaskForm(app,state,persist,ai,null,assistantDraft);
 else if(d.edit&&task(d.edit))showTaskForm(app,state,persist,ai,task(d.edit));
 else if('probe'in d)probe();
 else if('planner'in d||d.session)openPlanner(app,state,persist,d.session);
 else if(d.done||d.missed){recordProgress(state,{blockId:d.done||d.missed,status:d.done?'completed':'missed'});persist('Session progress saved.');}
 else if(d.week){weekMode=d.week;render();}
 else if(d.agenda){if(agendaMode===d.agenda)return;const items=app.querySelector('.agenda-items'),before=new Map([...items.querySelectorAll('.agenda-card')].map(c=>[c,c.getBoundingClientRect()]));agendaMode=d.agenda;items.classList.toggle('timeline',agendaMode==='timeline');items.classList.toggle('list',agendaMode==='list');app.querySelectorAll('[data-agenda]').forEach(b=>b.classList.toggle('chosen',b.dataset.agenda===agendaMode));if(!matchMedia('(prefers-reduced-motion: reduce)').matches)before.forEach((r,c)=>{const n=c.getBoundingClientRect();c.animate([{transform:`translate(${r.left-n.left}px,${r.top-n.top}px) scaleX(${r.width/n.width})`},{transform:'none'}],{duration:220,easing:'ease-out'});});}
 else if(d.delete)confirmAction('Delete task?','Its study sessions and plan history will also be removed.',()=>{state.tasks=state.tasks.filter(t=>t.id!==d.delete);state.blocks=state.blocks.filter(b=>b.taskId!==d.delete);state.history=[];persist('Task deleted.');});
 else if('sample'in d)confirmAction('Load sample week?','This replaces your planner. Export a backup first.',()=>{try{state=loadDemoFixtures();persist('Sample week loaded.');}catch(error){notice=error.message;failed=true;render();}});
 else if('export'in d){try{const url=URL.createObjectURL(new Blob([exportState(state)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='waypoint-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){notice=error.message;failed=true;render();}}
 else if('dismiss'in d){notice='';render();}
});
app.addEventListener('input',e=>{if(e.target.id==='assistant-draft'){assistantDraft=e.target.value;resizeDraft();}});
app.addEventListener('change',async e=>{if(e.target.id!=='backup-file')return;const file=e.target.files[0];if(!file)return;const text=await file.text();confirmAction('Import backup?','Replace the current planner with this backup?',()=>{try{state=importState(text).state;persist('Backup imported.');}catch(error){notice=error.message;failed=true;render();}});});
window.addEventListener('resize',resizeDraft);window.addEventListener('online',probe);window.addEventListener('offline',probe);render();probe();
