import {planWeek,repairPlan} from './scheduler.js';
import {acceptPlan,undoPlan,recordProgress} from './store.js';
import {parseInTimezone,formatDateTime,diffMinutes} from './dates.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openPlanner(app,state,persist,selectedId){
  let proposal=null;
  app.insertAdjacentHTML('beforeend','<dialog id="planner-dialog" aria-label="Study plan"><div class="dialog-body"></div></dialog>');
  const dialog=app.querySelector('#planner-dialog'),body=dialog.querySelector('.dialog-body');
  const name=id=>state.tasks.find(t=>t.id===id)?.title||'Removed task';
  function render(){body.innerHTML=`<div class="panel-title"><h2>Study plan</h2><button type="button" data-close>Close</button></div><p>Enter study availability and fixed commitments in Philippine time.</p><form id="window-form"><div class="form-row"><label>Type<select name="kind"><option value="availability">Study availability</option><option value="commitments">Fixed commitment</option></select></label><label>Title<input name="title" maxlength="180"></label></div><div class="form-row three"><label>Date<input name="date" type="date" required></label><label>Start<input name="start" type="time" required></label><label>End<input name="end" type="time" required></label></div><p id="window-error" role="alert"></p><button class="soft">Add window</button></form>${['availability','commitments'].map(kind=>`<hr><h3>${kind==='availability'?'Study availability':'Fixed commitments'}</h3>${state[kind].map(w=>`<p>${esc(w.title||'Study time')} · ${formatDateTime(w.startAt)} – ${formatDateTime(w.endAt)} <button type="button" data-remove="${esc(w.id)}" data-kind="${kind}">Remove</button></p>`).join('')||'<p>None entered.</p>'}`).join('')}<div class="actions"><button data-plan class="primary">Preview plan</button><button data-repair class="soft">Preview recovery</button>${state.history.length?'<button data-undo class="soft">Undo last plan</button>':''}</div>${proposal?`<hr><h3>Proposed changes</h3><p>Your saved calendar changes only after acceptance.</p>${proposal.changes.map(c=>`<p>${esc(c.type)} · ${esc(name(c.taskId))} · ${esc(c.reason)}${c.before?`<br>Before: ${formatDateTime(c.before.startAt)} – ${formatDateTime(c.before.endAt)}`:''}${c.after?`<br>After: ${formatDateTime(c.after.startAt)} – ${formatDateTime(c.after.endAt)}`:''}</p>`).join('')||'<p>No changes.</p>'}${proposal.unallocated.map(u=>`<p class="warning">${esc(name(u.taskId))}: ${u.minutes} min unscheduled · ${esc(u.reason)}</p>`).join('')}${proposal.warnings.map(w=>`<p>${esc(w.code)} · ${esc(name(w.id))}</p>`).join('')}<div class="actions"><button data-accept class="primary">Accept plan</button><button data-cancel class="soft">Cancel preview</button></div>`:''}<hr><h3>Saved sessions</h3>${state.blocks.filter(b=>state.tasks.some(t=>t.id===b.taskId)).map(b=>`<article class="inset" data-block="${esc(b.id)}" tabindex="-1"><h3>${esc(name(b.taskId))}</h3><p>${formatDateTime(b.startAt)} – ${formatDateTime(b.endAt)} · ${esc(b.status)}${b.locked?' · Locked':''}</p>${b.status==='planned'?`<button data-lock="${esc(b.id)}">${b.locked?'Unlock':'Lock'}</button><button data-partial="${esc(b.id)}">Record partial</button><button data-done="${esc(b.id)}">Done</button><button data-missed="${esc(b.id)}">Missed</button>`:''}</article>`).join('')||'<p>No scheduled sessions.</p>'}`;}
  function save(message){const result=persist(message,false);proposal=null;render();const p=document.createElement('p');p.textContent=result.message;p.setAttribute('role',result.ok?'status':'alert');p.classList.toggle('warning',!result.ok);body.prepend(p);}
  body.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();if(e.target.id!=='window-form')return;const f=new FormData(e.target);if(f.get('end')<=f.get('start')){body.querySelector('#window-error').textContent='End must be later than start.';return;}if(f.get('kind')==='commitments'&&!f.get('title').trim()){body.querySelector('#window-error').textContent='Enter a commitment title.';return;}state[f.get('kind')].push({id:crypto.randomUUID(),title:f.get('title').trim(),startAt:parseInTimezone(f.get('date'),f.get('start')),endAt:parseInTimezone(f.get('date'),f.get('end'))});save('Planning window saved.');});
  body.addEventListener('click',e=>{e.stopPropagation();const d=e.target.closest('button')?.dataset;if(!d)return;
    if('close'in d)dialog.close();
    else if('back'in d)render();
    else if(d.remove){state[d.kind]=state[d.kind].filter(w=>w.id!==d.remove);save('Window removed.');}
    else if('plan'in d||'repair'in d){proposal=('repair'in d?repairPlan:planWeek)(state,{now:new Date().toISOString()});render();}
    else if('cancel'in d){proposal=null;render();}
    else if('accept'in d){acceptPlan(state,proposal);save('Study plan accepted.');}
    else if('undo'in d){undoPlan(state);save('Previous plan restored.');}
    else if(d.lock){const b=state.blocks.find(b=>b.id===d.lock);b.locked=!b.locked;save('Session lock updated.');}
    else if(d.partial){const b=state.blocks.find(b=>b.id===d.partial),t=state.tasks.find(t=>t.id===b.taskId);const maximum=Math.min(diffMinutes(b.startAt,b.endAt),b.completedMinutes+t.remainingMinutes);if(maximum<=b.completedMinutes)return;body.innerHTML=`<button type="button" data-back>Back to study plan</button><h2>Record progress</h2><form id="progress-form"><label>Total minutes completed in this session<input name="minutes" type="number" min="${b.completedMinutes+1}" max="${maximum}" required></label><button class="primary">Save progress</button></form>`;body.querySelector('form').addEventListener('submit',event=>{event.preventDefault();event.stopPropagation();recordProgress(state,{blockId:b.id,completedMinutes:Number(new FormData(event.target).get('minutes')),status:'partially_completed'});save('Progress saved.');});}
    else if(d.done||d.missed){recordProgress(state,{blockId:d.done||d.missed,status:d.done?'completed':'missed'});save('Progress saved. Preview recovery for remaining work.');}
  });
  dialog.addEventListener('close',()=>{dialog.remove();persist('',true);});render();dialog.showModal();if(selectedId){const card=body.querySelector(`[data-block="${CSS.escape(selectedId)}"]`);card?.scrollIntoView({block:'center'});card?.focus();}
}
