import {interpretTask} from './ai-client.js';
import {toLocalDateAndTime,parseInTimezone} from './dates.js';
import {createTask} from './model.js';
import {reviewEstimate} from './task-draft-ui.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function showTaskForm(app,state,persist,ai,task=null,initialText=''){
  let controller=null,steps=task?.steps||[],sourceText=task?.sourceText||'',estimate=null;
  const due=task?.dueAt?toLocalDateAndTime(task.dueAt):{date:'',time:'23:59'};
  app.insertAdjacentHTML('beforeend',`<dialog id="task-dialog" aria-label="${task?'Edit task':'Add task'}"><form id="task-form"><div class="dialog-head"><h2>${task?'Edit task':'Add Task'}</h2><button type="button" data-close aria-label="Close task dialog">Close</button></div><div class="dialog-body"><div class="inset capture"><h3>Describe a task</h3><p>${ai.ready?'Local AI is ready. Review the extracted details before saving.':'Local AI is unavailable. You can enter every field manually.'}</p><label>Task description<textarea id="capture-text" maxlength="4000" placeholder="MATH 54 problem set due Friday, about 2 hours">${esc(initialText)}</textarea></label><div class="actions"><button class="primary" type="button" data-interpret ${ai.ready?'':'disabled'}>Interpret</button><button class="soft" type="button" data-cancel hidden>Cancel interpretation</button></div><p id="capture-feedback" role="status"></p><button class="soft" type="button" data-estimate hidden>Use suggested estimate</button></div><label>Task title<input name="title" required maxlength="180" value="${esc(task?.title||'')}"></label><div class="form-row"><label>Course (optional)<input name="course" maxlength="60" value="${esc(task?.course||'')}"></label><label>Remaining work (minutes)<input name="minutes" type="number" min="0" max="10080" required value="${task?.remainingMinutes??60}"></label></div><div class="form-row"><label>Due date (optional)<input name="dueDate" type="date" value="${due.date}"></label><label>Due time (PHT)<input name="dueTime" type="time" value="${due.time}"></label></div><label>Next step (optional)<input name="step" maxlength="250" value="${esc(steps[0]?.title||'')}"></label><p id="form-error" role="alert"></p><p>No calendar changes occur until you save and accept a scheduling proposal.</p></div><footer class="dialog-footer"><button type="button" data-close>Cancel</button><button class="primary" data-save>Save Task</button></footer></form></dialog>`);
  const dialog=app.querySelector('#task-dialog'),form=dialog.querySelector('form'),feedback=dialog.querySelector('#capture-feedback');
  const field=name=>form.elements.namedItem(name);
  dialog.addEventListener('close',()=>{controller?.abort();dialog.remove();});
  dialog.addEventListener('click',async e=>{e.stopPropagation();const d=e.target.closest('button')?.dataset;if(!d)return;
    if('close'in d)dialog.close();
    else if('cancel'in d)controller?.abort();
    else if('estimate'in d){field('minutes').value=estimate;field('minutes').classList.remove('missing-field');feedback.textContent='Suggested estimate filled. Review it before saving.';}
    else if('interpret'in d){const text=dialog.querySelector('#capture-text').value.trim();if(!text){feedback.textContent='Describe the assignment first.';return;}controller=new AbortController();const request=controller;dialog.querySelector('[data-interpret]').disabled=true;dialog.querySelector('[data-cancel]').hidden=false;dialog.querySelector('[data-save]').disabled=true;feedback.textContent='Interpreting locally… This may take 15–45 seconds. Manual fields remain editable.';
try{const result=await interpretTask(text,{currentDate:new Date().toISOString(),timezone:'Asia/Manila'},{signal:request.signal});if(!dialog.isConnected||request.signal.aborted)return;const draft=result.draft;sourceText=text;steps=draft.steps||[];field('title').value=draft.title||'';field('course').value=draft.course||'';const deadline=draft.dueAt?toLocalDateAndTime(draft.dueAt):{date:'',time:'23:59'};field('dueDate').value=deadline.date;field('dueTime').value=deadline.time;field('step').value=steps[0]?.title||'';const effort=reviewEstimate(draft);estimate=effort.suggested;field('minutes').value=effort.confirmed??'';dialog.querySelector('[data-estimate]').hidden=estimate==null;dialog.querySelector('[data-estimate]').textContent=`Use suggested estimate (${estimate} min)`;dialog.querySelectorAll('.missing-field').forEach(el=>el.classList.remove('missing-field'));const mapping={title:'title',course:'course',dueAt:'dueDate',estimatedMinutes:'minutes'};(draft.missingFields||[]).forEach(key=>field(mapping[key]||key)?.classList.add('missing-field'));feedback.textContent=`Review your draft. ${result.meta.modelUsed} · ${result.meta.latencyMs==null?'Latency unavailable':(result.meta.latencyMs/1000).toFixed(1)+' s'}. Missing: ${(draft.missingFields||[]).join(', ')||'none'}. ${(draft.warnings||[]).join(' ')}`;
      }catch(error){if(dialog.isConnected)feedback.textContent=request.signal.aborted?'Interpretation cancelled. Enter manually or try again.':({OFFLINE:'Start Ollama, then retry. Manual entry is available.',TIMEOUT:'Took too long. Try again or enter manually.',MALFORMED_OUTPUT:'Couldn’t read that. Try rephrasing.'}[error.code]||error.message);}
      finally{if(dialog.isConnected){dialog.querySelector('[data-interpret]').disabled=!ai.ready;dialog.querySelector('[data-cancel]').hidden=true;dialog.querySelector('[data-save]').disabled=false;}controller=null;}
    }
  });
form.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();if(controller)return;try{const f=new FormData(form),minutes=Number(f.get('minutes'));const editedStep=f.get('step').trim();const nextSteps=steps.map(s=>({...s}));if(editedStep){if(nextSteps.length)nextSteps[0].title=editedStep;else nextSteps.push({title:editedStep});}else if(nextSteps.length)nextSteps.shift();const t=createTask({id:task?.id,title:f.get('title'),course:f.get('course'),remainingMinutes:minutes,status:minutes===0?'done':'open',dueAt:f.get('dueDate')?parseInTimezone(f.get('dueDate'),f.get('dueTime')||'23:59'):null,steps:nextSteps,sourceText:sourceText||dialog.querySelector('#capture-text').value.trim()});if(task)state.tasks=state.tasks.map(item=>item.id===task.id?t:item);else state.tasks.push(t);dialog.close();persist('Task saved. Open Week to preview a study plan.');}catch(error){dialog.querySelector('#form-error').textContent=error.message;}});
  dialog.showModal();field('title').focus();
}
